gentoo-haskell/gentoo-haskell

app-emacs/haskell-mode/haskell-mode-9999.ebuild

This commit changes the `EGIT_REPO_URI` of
`app-emacs/haskell-mode-9999` to always use the HTTPS Git transport
protocol, rather than either that or the plain Git transport protocol.
The only reasonable scenario I see in which the plain Git transport
would work and the HTTPS transport wouldn’t is that of HTTPS being
blocked by an attacker wishing to force the download to occur via the
unsecured plain Git transport, enabling the injection of malware.

Always fetch app-emacs/haskell-mode-9999 via HTTPS

---

dev-lang/idris/idris-9999.ebuild

**[DO NOT MERGE YET]**
It works fine with ghc 7.10.2, unfortunately, there's some issue:
```
../../dist/build/idris/idris: error while loading shared libraries: libHSidris-0.9.18.1-7S2dH0MQ9Dd1NbPfauOd39-ghc7.10.2.so: cannot open shared object file: No such file or directory
```
How can I build idris statically?

dev-lang/idris: update 9999 version

---

app-emacs/ghc-mod/ghc-mod-9999.ebuild

With this change, now I can emerge ghc-mod-9999 successfully.
I have tested with ghc-7.10.2-r1::gentoo.
The following is the error log that emerging ghc-mod-9999 generated.
~~~
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) app-emacs/ghc-mod-9999::haskell
>>> Failed to emerge app-emacs/ghc-mod-9999, Log file:
>>>  '/tmp/portage/app-emacs/ghc-mod-9999/temp/build.log'
* Package:    app-emacs/ghc-mod-9999
* Repository: haskell
* Maintainer: haskell@gentoo.org
* USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
* FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
GIT update -->
repository:               https://github.com/kazu-yamamoto/ghc-mod.git
at the commit:            0fde762500016d00ff3bed32d8dfca6e1b351b55
branch:                   master
storage …

Add pipes-4.1 to the dependency of app-emacs/ghc-mod-9999

---

eclass/haskell-cabal.eclass

I suppose build-type: simple allows having no Setup.hs and this was unexpected for me when src_configure died without it

create simple Setup.hs instead of dieng in case if missing one

---

dev-haskell/cairo/cairo-0.13.3.0.ebuild

dev-haskell/cairo requires dev-haskell/gtk2hs-buildtools for
compilation, but this dependency has been accidentally removed from the
ebuild during the bump to 0.13.3.0

dev-haskell/cairo-0.13.3.0: Re-add dep on gtk2hs-buildtools

---

dev-vcs/git-annex/git-annex-6.20170101.ebuild

In commit 9397f499c, crypto-api was added to git-annex.cabal, but not to
the ebuild's RDEPEND.
Bug: https://github.com/gentoo-haskell/gentoo-haskell/issues/568

dev-vcs/git-annex-6.20170101: Add crypto-api dependency

---

x11-misc/taffybar/taffybar-9999.ebuild

Add dependency on dev-haskell/either.
See: https://github.com/travitch/taffybar/commit/ce0816296f63711dac05ff005768203e31f9ab39

x11-misc/taffybar: refresh live ebuild

---

app-portage/hackport/hackport-0.5.2.ebuild
app-portage/hackport/hackport-0.5.3.ebuild
app-portage/hackport/hackport-0.5.4.ebuild
app-portage/hackport/hackport-9999.ebuild

While most devs will already have repoman merged, listing it explicitly makes it that much smoother for newcomers (like me). Besides, it allows dropping it from `@world` if anyone doesn't use it directly.
repoman itself complains about the <sys-apps/portage-2.3.0 not matching any packages, but I thought it would be better to leave it in for the out-of-date repos that do still provide early versions.

Add repoman to dependencies for hackport

---

dev-lang/elm-reactor/elm-reactor-0.18.0.ebuild

Add a build-time dependency on elm-make to avoid the error below. Fixed in-place because this is a build error and it may not have affected people because it depends on the merge order.
>> Compiling source in /var/tmp/portage/dev-lang/elm-reactor-0.18.0/work/elm-reactor-0.18.0 ...
./setup build
Building elm-reactor-0.18...
Preprocessing executable 'elm-reactor' for elm-reactor-0.18...
[1 of 8] Compiling StaticFiles.Build ( src/backend/StaticFiles/Build.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles/Build.dyn_o )
[2 of 8] Compiling StaticFiles      ( src/backend/StaticFiles.hs, dist/build/elm-reactor/elm-reactor-tmp/StaticFiles.dyn_o )
src/backend/StaticFiles.hs:50:3: error:
• Exception when trying to run compile-time code:
elm-make: readCreateProcessWithExitCode: …

dev-lang/elm-reactor: add missing dependency on elm-make

---

README.rst

I have updated the layman installation instructions in the README to be in line with the latest instructions from the Gentoo Wiki layman entry. I have also added instructions on using the eselect-repository tool instead of layman, which may be simpler.

Update README overlay set up instructions

---

dev-haskell/repa/repa-3.4.1.3-r1.ebuild

The upper bound for `base` in this version is 4.12, not 4.11.
Package-Manager: Portage-2.3.40, Repoman-2.3.9

dev-haskell/repa: correct upper bound on base dependency in 3.4.1.3-r1

---

profiles/package.mask

There are a couple of reasons for unmasking these packages.
Firstly, unmasking the newer versions of blaze-markup and
blaze-html does not appear to cause any conflicts. The mask
was originally applied on 6 January 2018 because not enough
packages had been ported to use these newer versions. This
appears to have changed.
I have git grepped the overlay for "<dev-haskell/blaze-markup-0.8"
and "<dev-haskell/blaze-html-0.9". For each grep I checked:
(1) the listed packages for newer versions which depend on
the masked versions of blaze-markup and blaze-html; and
(2) for conflicts caused by updating to the newer packages which
rely on the masked versions of blaze-markup and blaze-html.
I accept that manually checking these things is not the most robust
procedure, but from this I determined that …

profiles/package.mask: unmask blaze-markup and blaze-html

---

dev-haskell/language-glsl/files/language-glsl-0.2.1-prelude-hiding.patch
dev-haskell/language-glsl/language-glsl-0.2.1-r1.ebuild

Apply patch which hides Prelude.(<>) to solve ambiguity in Pretty.hs.
Package-Manager: Portage-2.3.44, Repoman-2.3.10

dev-haskell/language-glsl: fix compatibility with ghc 8.4

---

profiles/package.mask

`config-ini-0.2.2` is only compatible with `megaparsec-6`, which has just been unmasked in the overlay. Unmask `>=dev-haskell/config-ini-0.2` to fix compatibility with `megaparsec-6`.
To the best of my knowledge there are no reverse dependencies conflicting with this unmask.

profiles/package.mask: unmask >=dev-haskell/config-ini-0.2

---

dev-haskell/concurrent-extra/concurrent-extra-0.7.0.12.ebuild

Test fails on `stresstest`, all other pass. Built with ghc 8.4.
Package-Manager: Portage-2.3.44, Repoman-2.3.10

dev-haskell/concurrent-extra: restrict test

---

dev-haskell/flac/flac-0.1.2.ebuild

RDEPEND allowed exceptions-0.10, but the cabal file did not.
Package-Manager: Portage-2.3.44, Repoman-2.3.10

dev-haskell/flac: allow exceptions-0.10

---

dev-haskell/tagsoup-megaparsec/tagsoup-megaparsec-0.2.0.0.ebuild
profiles/package.mask

tagsoup-megaparsec is now masked in profiles/package.mask. The keywords have been restored in the ebuild.

Adjust tagsoup-megaparsec mask

---

dev-haskell/pandoc-crossref/pandoc-crossref-0.2.6.0-r1.ebuild

Note that I couldn't test the build of this on ghc 8.4, since the current version of `pandoc` in the overlay is incompatible.
I assume the problem is the recent bump of `pandoc-types`. Is it enough to tighten the upper bound on `pandoc-types` without putting a hard mask in profiles/package.mask?
Closes: https://github.com/gentoo-haskell/gentoo-haskell/issues/797
Package-Manager: Portage-2.3.45, Repoman-2.3.10

dev-haskell/pandoc-crossref: tighten upper bound on pandoc-types

---

dev-haskell/resolv/resolv-0.1.1.1.ebuild

Fails to build test suite. `dev-haskell/resolv` is required by `=dev-haskell/cabal-install-2.2.0.0`.
Package-Manager: Portage-2.3.46, Repoman-2.3.10
Error message:
Building test suite 'resolv.' for resolv-0.1.1.1..
[1 of 1] Compiling Main             ( src-test/Tests1.hs, dist/build/resolv./resolv.-tmp/Main.dyn_o )
src-test/Tests1.hs:81:53: error:
• Couldn't match type ‘[Char]’ with ‘Maybe GHC.Stack.Types.SrcLoc’
Expected type: Maybe GHC.Stack.Types.SrcLoc
Actual type: String
• In the first argument of ‘T.HUnitFailure’, namely ‘msg’
In the first argument of ‘E.throwIO’, namely ‘(T.HUnitFailure msg)’
In the expression: E.throwIO (T.HUnitFailure msg)
|
81 | assertJust msg Nothing  = E.throwIO (T.HUnitFailure msg)
|                                                     ^^^

dev-haskell/resolv: restrict tests

---

profiles/package.mask

The masks on `servant-client` and `servant-client-core` are no longer necessary.

profiles/package.mask: unmask servant-client and dependencies

---

.travis.yml
dev-haskell/ansi-terminal/ansi-terminal-0.8.0.4.ebuild
profiles/package.mask

* Unmask `dev-haskell/skylighting-core` for `dev-haskell/skylighting-0.7.2`
* Drop all keywords except for `amd64` and `x86` in `dev-haskell/ansi-terminal-0.8.0.4` since the dependency `dev-haskell/colour` does not exist on other arches.

Fix ci failures

---

dev-haskell/hsyaml/hsyaml-0.1.1.2.ebuild

Trying to install with dlist-0.8.0.2 produces the following error. Succeeds with 0.8.0.4.
```
Preprocessing library for HsYAML-0.1.1.2..
Building library for HsYAML-0.1.1.2..
[1 of 7] Compiling Util             ( src/Util.hs, dist/build/Util.o )
[2 of 7] Compiling Data.YAML.Token.Encoding ( src/Data/YAML/Token/Encoding.hs, dist/build/Data/YAML/Token/Encoding.o )
[3 of 7] Compiling Data.YAML.Token  ( src/Data/YAML/Token.hs, dist/build/Data/YAML/Token.o )
src/Data/YAML/Token.hs:28:1: error:
Data.DList: Can't be safely imported! The module itself isn't safe.
```

dev-haskell/hsyaml: Update dlist dep

---

profiles/package.mask

ghc-mod requires porting to ghc 8.4.

profiles/package.mask: mask app-emacs/ghc-mod

---

dev-haskell/deriving-compat/deriving-compat-0.3.6.ebuild

Tests fail to compile and have been disabled.
Package-Manager: Portage-2.3.48, Repoman-2.3.10

dev-haskell/deriving-compat: allow template-haskell 2.13

---

dev-haskell/keter/files/keter-1.4.3.2-http-reverse-proxy-0.6.0.patch

These adjustments allow for versions of http-reverse-proxy
earlier than 0.6.0 to also be compatible with keter.
Package-Manager: Portage-2.3.48, Repoman-2.3.10

dev-haskell/keter: adjust http-reverse-proxy patch

---

dev-haskell/http/http-4000.3.12.ebuild

https://hackage.haskell.org/package/HTTP-4000.3.12/revisions/
Signed-off-by: Harri Nieminen <moikkis@gmail.com>
Package-Manager: Portage-2.3.49, Repoman-2.3.11

dev-haskell/http: Allow base-4.12

---

dev-haskell/happy/happy-1.19.9.ebuild

http://hackage.haskell.org/package/happy-1.19.9/revisions/
Package-Manager: Portage-2.3.49, Repoman-2.3.11

dev-haskell/happy: Allow cabal-2.4

---

x11-misc/xmobar/xmobar-0.28.ebuild

https://github.com/jaor/xmobar/commit/5c571e757718f41889d45406529bc39e10baf55c
Signed-off-by: Harri Nieminen <moikkis@gmail.com>
Package-Manager: Portage-2.3.50, Repoman-2.3.11

x11-misc/xmobar: Allow base-4.13 and stm-2.5

---

dev-haskell/reactive-banana-wx/reactive-banana-wx-1.1.1.0-r1.ebuild

include support for reactive-banana-1.2.*
This compiles with `dev-haskell/reactive-banana-1.2.0.0` and the examples run fine on my system.

dev-haskell/reactive-banana-wx: Bump to 1.1.1.0-r1 

---

dev-haskell/beam-core/beam-core-0.7.2.2-r1.ebuild
dev-haskell/beam-migrate/beam-migrate-0.3.2.1-r1.ebuild
dev-haskell/beam-postgres/beam-postgres-0.3.2.2-r1.ebuild

`beam-core` has been revised upstream to no longer allow `free >= 5.1`
This updates the ebuild and adds the latest version of `free` which meets this new constraint.

dev-haskell/beam-core: Bump to 0.7.2.2-r1

---

eclass/darcs.eclass
eclass/ghc-package.eclass
eclass/haskell-cabal.eclass

I've opened this PR for discussion and review, given the changes touch the eclasses.
`darcs.eclass`, `ghc-package.eclass` and `haskell-cabal.eclass` have been updated to be compatible with ebuilds using EAPI 7, with the intention of maintaining compatibility with earlier EAPIs.
The main change is eliminating `versionator` from `ghc-package.eclass`, and replacing `version_is_at_least` with `ver_test` from either `eapi7-ver.eclass` for ebuilds not yet using EAPI 7, or the built-in `ver-test` for ebuilds using EAPI 7.
One issue with this is that it seems that `eapi7-ver.eclass` doesn't appear to be intended for general use, but rather for testing EAPI 7's new versioning functions before they were formally released. Nevertheless it appears to work.
Bug: …

eclass: update eclasses for EAPI 7

---

dev-haskell/encoding/encoding-0.8.2.ebuild
dev-haskell/encoding/files/encoding-0.8.2-ghc-865.patch

Library seems to be abandoned but still fully compatible with containers-0.6+
Tested on ghc-8.6.4

dev-haskell/encoding tweak for ghc-8.6.5

---

dev-haskell/yesod-bin/yesod-bin-1.6.0.3-r2.ebuild

yesod-bin-1.6.0.3 in hackage mistakenly restricts fsnotify to '< 0.3'. Both the hackage description itself and the upstream repo on github specify < 0.4.

yesod-bin-1.6.0.3 broken dependency

---

dev-lang/elm-compiler/elm-compiler-0.19.0-r1.ebuild

Found out the dependency on the haskell package containers was missing. Added the appropriate version as dependency to ebuild.
Feedback is greatly appreciated since this is my first contribution around here :)

Elm-compiler: Added dependency on haskell package 'containers'

---

dev-vcs/git-annex/files/git-annex-7.20190129-socks-0.6.patch
dev-vcs/git-annex/git-annex-7.20190129.ebuild

Pull changes from `git-annex` upstream [094c91aacd24cff5394fed74a64bbbba77b7498b](http://source.git-annex.branchable.com/?p=source.git;a=blobdiff;f=Utility/Tor.hs;h=094c91aacd24cff5394fed74a64bbbba77b7498b;hp=427fb100bc222ac58c4fd61059e02f606749f377;hb=018b5b81736a321f3eb9762a2afb7124e19dbdf9;hpb=9fd37e65d05c6169a81d066658776e0dc19e9495) as a patch to support `>=dev-haskell/socks-0.6`.

dev-vcs/git-annex: support >=socks-0.6

---

dev-haskell/mustache/files/mustache-2.3.1-r1-either.patch
dev-haskell/mustache/mustache-2.3.1-r1.ebuild

_dev-haskell/stack-2.3.3::haskell_ [**->**](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-haskell/stack/stack-2.3.3.ebuild#L59) _dev-haskell/mustache_ [**->**](https://github.com/gentoo-haskell/gentoo-haskell/blob/master/dev-haskell/mustache/mustache-2.3.1.ebuild#L24) [_either_](https://hackage.haskell.org/package/either) which was  [removed](https://github.com/gentoo-haskell/gentoo-haskell/commit/b578b260d8de1c70c590c0e8951a57c5ab57ac8c#diff-a22be0b35f0c09a54e0200743553e8e5c6287a3eb75d321e48bd093c6879e6ac) from ::haskell a while ago causing portage to pull [dev-haskell/either::gentoo](https://packages.gentoo.org/packages/dev-haskell/either) 
Looking up mustache [sources](https://github.com/JustusAdam/mustache) I haven't found any usage of [_dev-haskell/either …

dev-haskell/mustache rudimentary 'either' dep. drop

---

app-portage/hackport/hackport-9999.ebuild

Signed-off-by: Wolfgang E. Sanyer <WolfgangESanyer@gmail.com>

app-portage/hackport-9999 added missing dependency.

---

profiles/package.mask

I _think_ this would close #1043 . It seems to cause no issues on my system. What else is needed?

profiles/package.mask: Remove haskell-src-exts masks

---

.github/workflows/pkgcheck.yml
.github/workflows/repoman.yml

This PR will actually require a tweak after merge in order to fix the badge on the `README` - it currently links to my forked repo, but I don't really know what the link in the haskell repo will be until we add the github actions setup.
Below is a screenshot of how the badge will look once it is setup.
I'm interested in transitioning **away** from travis-ci **towards** github actions (I can add an action for repoman as well) since it is supported natively and seems to be a tad faster.
I'm also interested in updating this to, say, only run `pkgcheck scan --commits` when a PR is submitted, and also add checks to **not** run CI if certain keywords are present in the commit message. I think this should all be rather trivial to implement since it is all native to github.

Add GitHub workflow for pkgcheck CI

---

dev-haskell/beam-automigrate/beam-automigrate-0.1.2.0-r1.ebuild

Remove upper bound on pretty-simple dependency

dev-haskell/beam-automigrate: Bump to 0.1.2.0-r1

---

dev-haskell/rio-orphans/files/rio-orphans-0.1.1.0-add-monadloggerio.patch
dev-haskell/rio-orphans/rio-orphans-0.1.1.0-r1.ebuild

Patch creates a MonadLoggerIO instance for RIO
This has been reported to upstream:
https://github.com/commercialhaskell/rio/pull/230

dev-haskell/rio-orphans: Bump to 0.1.1.0-r1

---

dev-haskell/cabal/cabal-3.2.1.0-r1.ebuild

dev-haskell/cabal-3.2.1.0-r1: fix CABAL_CORE_LIB_GHC_PV for rev-bumped ghc

---

.github/workflows/pkgcheck.yml

Temporarily use a fork from '@osirisinferi'
Bug: https://github.com/gentoo-haskell/gentoo-haskell/issues/1227

.github/workflows/pkgcheck.yml: Temporary fix

---

sci-mathematics/agda/metadata.xml

After the bump to version 2.6.2, the long description was lost in the Metadata.xml. I simply restored it from the previous ebuild.

sci-mathematics/agda: Restore longdescription

---

dev-haskell/hakyll/hakyll-4.15.1.0.ebuild

Hi,
It looks like the `cabal_chdeps` parameter value is incorrect (https://github.com/jaspervdj/hakyll/blob/v4.15.1.0/hakyll.cabal#L249)
I've fixed chdep parameters to make hakyll build again.

Fix dev-haskell/hakyll pandoc dependency

---

dev-haskell/lua/lua-2.0.2.ebuild

I have Lua 5.1 and 5.4 installed on my system. The package relies on a system-wide installation of 5.3, which was not pulled in by portage, causing the build to fail. Manually installing 5.3 allowed the build to finish successfully.
The ebuild states:
```bash
RDEPEND=">=dev-lang/ghc-8.4.3:=
>=dev-lang/lua-5.3 <dev-lang/lua-5.4
"
```
To my understanding, portage considers the two Lua constraints separately, with my installed 5.1 satisfying `<dev-lang/lua-5.4` and my installed 5.4 satisfying `>=dev-lang/lua-5.3`. So I simply merged those two into a single `dev-lang/lua:5.3`. As people affected by this bug should not have a working installation of `dev-haskell/lua`, I did not consider a revision bump necessary.

dev-haskell/lua: fixed dependency on dev-lang/lua-5.3

---

README.rst

Suggested edit to README.rst to warn users about repository priorities.

Add overlay priority warning to `README.rst`

---

README.rst
x11-wm/xmonad/files/xmonad.desktop

sddm uses the ``NoDisplay`` field in the xmonad.desktop file to determine whether this session should be in the list of sessions selectable from the login screen. In the overlay this is set to ``true`` - so the session doesn't appear.

Update xmonad.desktop file to sddm displays the session - reference #1273

---

projects/doc/README.rst

Looks like the link for the git book is no longer correct in the developer readme. With this pull request, hopefully I have linked to the correct location for the book!

Updated link for git book

---

x11-misc/xmobar/xmobar-9999.ebuild

Compilation was failing with following error, so fixing it
```
setup: Encountered missing or private dependencies:
netlink >=1.1.1.0, timezone-olson >=0.2 && <0.3```

x11-misc/xmobar: adjust dependency version bounds

---

eclass/haskell-cabal.eclass

pkgcheck complains of redundant distfile renames for any
packages whose ${CABAL_P} is equal to its ${P}. In other
words, all-lowercase packages.
In the spirit of avoiding QA warnings as much as possible,
this small eclass change checks if ${CABAL_P} does not equal
${P} prior to proceeding with renaming the distfile.
Where they are equal, it uses the distfile un-renamed from
upstream. This makes pkgcheck happy.
Signed-off-by: Jack Todaro <solpeth@posteo.org>

haskell-cabal.eclass: avoid redundant distfile renaming

---

profiles/package.mask

Some of the global package.mask entries in ::gentoo were not overridden here yet. This leads to warnings like such:
```
!!! The following installed packages are masked:
- dev-haskell/path-0.9.2-r1::haskell (masked by: package.mask)
/var/db/repos/gentoo/profiles/package.mask:
```

Unmask the packages masked in ::gentoo

---

eclass/haskell-cabal.eclass

For using live (9999) cabal and cabal-install versions.
Eclass used to get wrong version of cabal because portage labels it 9999 but ghc knows it's 3.9

eclass/haskell-cabal: support for using cabal-9999 (live cabal ebuilds)

---

dev-haskell/http-media/http-media-0.8.0.0.ebuild

builds fine with ghc-9.2.4
revision bump is not an option yet: https://github.com/zmthy/http-media/issues/41

dev-haskell/http-media: allow newer bytestring

---

dev-haskell/direct-sqlite/direct-sqlite-2.3.27.ebuild

`haveusleep` and `systemlib` are interpreted on other lines. Also, `-systemlib` misses `--flag=` prefix, causing configure to fail.

dev-haskell/direct-sqlite fix flags

---

dev-haskell/alex/alex-3.2.7.2.ebuild

Fix building `dev-haskell/alex` without `USE="doc"`.

dev-haskell/alex: fix no doc

---

app-text/pandoc-cli/pandoc-cli-0.1.1.ebuild
dev-haskell/pandoc/pandoc-3.1.8.ebuild
virtual/pandoc/pandoc-0.ebuild

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adapted from `virtual/pandoc-0::gentoo`.  This is needed to unblock dependents regardless of source ebuild repository.  (For example, see <https://bugs.gentoo.org/913960#c4>.)  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~I've opened this PR as a draft since there may still be a couple issues I have to resolve on it before it's fully ready to review.  Running '`pkgcheck scan`' outputs:~~  
```
virtual/pandoc
NonsolvableDepsInDev: version 0: nonsolvable depset(rdepend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (42 total): solutions: [ app-text/pandoc-bin[pandoc-symlink], app-text/pandoc-cli ]
NonsolvableDepsInStable: version 0: nonsolvable depset(rdepend) keyword(~riscv) stable profile (default/linux/riscv/20.0/rv64gc/lp64) (38 total): …
```

virtual/pandoc:  new package, add 0

---

eclass/ghc-package.eclass

See
https://github.com/gentoo/gentoo/commit/7c9bacebd7254491a72e633b523feacfec72d5ec

ghc-package.eclass: sync back from ::gentoo, fix  "unknown keyword @AUTHOR:" eclass-to-manpage error

---

dev-lang/ghc/ghc-9.4.5.ebuild
dev-lang/ghc/ghc-9.6.2.ebuild

This adds a couple seds in src_prepare to modify the settings file of the ghc bootstrap binary to make sure that the binary ghc uses the correct compiler and binutils.
Closes: https://github.com/gentoo-haskell/gentoo-haskell/issues/1463

dev-lang/ghc: make bootstrap binary comply with user's set compiler

---

README.rst

Layman has been deprecated and removed from portage. This pull request removes the instructions to use layman to install the repository.

Update README.rst - remove reference to using layman

---

dev-haskell/double-conversion/double-conversion-2.0.5.0.ebuild
dev-haskell/ghc-debug-stub/ghc-debug-stub-0.6.0.0.ebuild
dev-haskell/text/text-2.0.2.ebuild
dev-haskell/text/text-2.1.1.ebuild
dev-haskell/tidal-link/tidal-link-1.0.3.ebuild

Ran into some issues updating haskell-language-server as (some versions of) `dev-haskell/text` and `dev-haskell/double-conversation` still reference sys-devel/clang.
This changes those two packages, along with `dev-haskell/ghc-debug-stub` and `dev-haskell/tidal-link` which both also have the same issues.
Was considering adding -r1 to the versions, but after looking at a few examples from the main gentoo repo it looks like that isn't necessary for package name updates.

change old references to sys-devel/clang to llvm-core/clang in 4 packages

---

dev-haskell/glut/glut-2.7.0.16.ebuild

As far as I can see, this was the last failing port in @haskell-platform

dev-haskell/glut: loosening deps for ghc-9.12

---

scripts/package.unmask/ghc-9.6

dev-haskell/haddock-2.29.2 requires ghc>=9.8
(p.s.: note that there is actually no such thing as haddock-2.29.2 on hackage, this was a workaround by hololeap)
---
- [ x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [ x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [ x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [ x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.
Please note that all boxes must be …

scripts/package.unmask: ghc-9.6, stricter mask on haddock

---

dev-haskell/gtk/gtk-0.15.9.ebuild

Fixing a mistake in a previous commit. These lines should not have been dropped.
I’m awfully sorry for that
---

dev-haskell/gtk: reinstating GHC_BOOTSTRAP_PACKAGES

---

dev-haskell/byline/byline-1.1.2-r1.ebuild
dev-haskell/byline/files/byline-1.1.2-optparse-applicative-0.18.patch

When we moved from the local patch to the one submitted upstream, I overlooked the fact that some of the bits of the upstream patch were initially taken care of in CABAL_CHDEPS here, so the package was broken. This fixes it.
---

dev-haskell/byline: patch fix

---

dev-haskell/gtk2hs-buildtools/files/gtk2hs-buildtools-0.13.11.0-cabal-3.14.patch
dev-haskell/gtk2hs-buildtools/gtk2hs-buildtools-0.13.11.0.ebuild

This makes gtk2hs-buildtools build with ghc-9.12 (and lower versions, obviously)
---

dev-haskell/gtk2hs-buildtools: patching for ghc-9.12

---

dev-haskell/influxdb/influxdb-1.9.3.2.ebuild

I'm currently unable to run tests on this, not because they don't work, but because I cannot, for the life of me, get a version of influxdb that accepts to talk with this package, whether the pre-loosening or post-loosening version, and whichever version of ghc I use.
I have never used influxdb, the package only works with <influxdb-2.0, and I can only find doc for >=influxdb-2.0 online. Happy for some pointers.
---

dev-haskell/influxdb: loosening deps

---

dev-haskell/yesod-core/files/yesod-core-1.6.26.0-wai-extra.patch
dev-haskell/yesod-core/yesod-core-1.6.26.0.ebuild

#1642 
putting this one up alone as if I’m not mistaken it was blocking c. 25 other packages
---

dev-haskell/yesod-core: patch for wai-extra

---

dev-lang/ghc/ghc-9.10.1-r6.ebuild
dev-lang/ghc/ghc-9.12.1-r2.ebuild
dev-lang/ghc/ghc-9.12.2.ebuild
dev-lang/ghc/ghc-9.2.7-r1.ebuild
dev-lang/ghc/ghc-9.2.8.ebuild
dev-lang/ghc/ghc-9.4.7.ebuild
dev-lang/ghc/ghc-9.4.8.ebuild
dev-lang/ghc/ghc-9.6.3-r1.ebuild
dev-lang/ghc/ghc-9.6.4-r1.ebuild
dev-lang/ghc/ghc-9.6.5.ebuild
dev-lang/ghc/ghc-9.6.6.ebuild
dev-lang/ghc/ghc-9.8.2-r4.ebuild
dev-lang/ghc/ghc-9.8.3-r1.ebuild
dev-lang/ghc/ghc-9.8.4.ebuild

At the very least, 9.10.1 requires clang to build with `USE=llvm`. Adding `llvm-core/clang` as a dependency for `USE=llvm` for all versions, just to be safe.
---

dev-lang/ghc: Add clang as a llvm dep
